import"./assets/styles-CqwNybf1.js";import{a,i as r}from"./assets/vendor-BO1i2NM4.js";const g="https://dummyjson.com",n={CATEGORIES:"/products/category-list",PRODUCTS:"/products",SEARCH:"/products/search"},u=12;a.defaults.baseURL=g;const E=async()=>{const{data:t}=await a.get(n.CATEGORIES);return t},m=async t=>{const{data:o}=await a.get(`${n.PRODUCTS}`,{params:{limit:u,skip:(t-1)*u}});return o},y=async(t,o)=>{const{data:s}=await a.get(`${n.SEARCH}`,{params:{limit:u,q:t}});return s},b=async t=>{const{data:o}=await a.get(`${n.PRODUCTS}/${t}`);return o},e={ulCategorEl:document.querySelector(".categories"),ulProductEl:document.querySelector(".products"),searchFormEl:document.querySelector(".search-form"),clearBtnForm:document.querySelector(".search-form__btn-clear"),notFoundEl:document.querySelector(".not-found"),modalEl:document.querySelector(".modal"),modalCloseBtn:document.querySelector(".modal__close-btn"),modalListEl:document.querySelector(".modal-product"),loadMoreBtn:document.querySelector(".load-more-btn"),loaderEl:document.querySelector(".loader"),scrollToTopBtn:document.querySelector(".scroll-top-btn")},h=t=>{const o=t.map(s=>`<li class="categories__item">
   <button class="categories__btn" type="button">${s}</button>
 </li>`).join("");e.ulCategorEl.innerHTML=o},p=t=>{const o=t.map(s=>`<li class="products__item" data-id="${s.id}">
    <img class="products__image" src="${s.thumbnail}" alt="${s.description}"/>
    <p class="products__title">${s.title}</p>
    <p class="products__brand"><span class="products__brand--bold">Brand: ${s.brand}</span></p>
    <p class="products__category">Category: ${s.category}</p>
    <p class="products__price">Price: ${s.price}$</p>
 </li>`).join("");e.ulProductEl.insertAdjacentHTML("beforeend",o)},L=t=>{e.ulProductEl.innerHTML="";const o=t.map(s=>`<li class="products__item" data-id="${s.id}">
    <img class="products__image" src="${s.thumbnail}" alt="${s.description}"/>
    <p class="products__title">${s.title}</p>
    <p class="products__brand"><span class="products__brand--bold">Brand: ${s.brand}</span></p>
    <p class="products__category">Category: ${s.category}</p>
    <p class="products__price">Price: ${s.price}$</p>
 </li>`).join("");e.ulProductEl.innerHTML=o},v=t=>{const o=`<img class="modal-product__img" src="${t.thumbnail}" alt="${t.description}" />
      <div class="modal-product__content">
        <p class="modal-product__title">${t.title}</p>
        <ul class="modal-product__tags">${t.tags}</ul>
        <p class="modal-product__description">${t.description}</p>
        <p class="modal-product__shipping-information">Shipping: ${t.shippingInformation}</p>
        <p class="modal-product__return-policy">Return Policy: ${t.returnPolicy}</p>
        <p class="modal-product__price">Price: ${t.price}$</p>
        <button class="modal-product__buy-btn" type="button">Buy</button>
      </div>
`;e.modalListEl.innerHTML=o},f=t=>t?!0:(r.warning({message:"Введіть значення для пошуку"}),!1),$=t=>!t.products||t.products.length===0?(r.warning({message:"Нічого не знайдено"}),!1):!0,B=()=>{e.clearBtnForm.addEventListener("click",()=>{e.ulProductEl.innerHTML="",e.searchFormEl.searchValue.value="",e.clearBtnForm.classList.remove("search-form__btn-clear--visible"),e.notFoundEl.classList.remove("not-found--visible"),_()})},P=()=>{window.addEventListener("scroll",()=>{window.scrollY>400?e.scrollToTopBtn.classList.add("scroll-top-btn--visible"):e.scrollToTopBtn.classList.remove("scroll-top-btn--visible")}),e.scrollToTopBtn.addEventListener("click",()=>{window.scrollTo({top:0,behavior:"smooth"})})};let c=1,l,d=0;const T=async()=>{try{const t=await E();h(["All",...t])}catch(t){r.error({message:t})}},_=async()=>{try{const t=await m(c);p(t.products),d=Math.ceil(t.total/t.limit),c<d?e.loadMoreBtn.classList.remove("is-hidden"):e.loadMoreBtn.classList.add("is-hidden")}catch(t){r.error({message:t})}e.loadMoreBtn.addEventListener("click",async()=>{e.loadMoreBtn.classList.add("is-hidden"),e.loaderEl.classList.add("is-visible"),c++;const t=await m(c);p(t.products),e.loaderEl.classList.remove("is-visible"),e.loadMoreBtn.classList.remove("is-hidden");const o=document.querySelector(".products__item");if(o){const s=o.getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"})}c>=d&&(e.loadMoreBtn.classList.add("is-hidden"),r.info({message:"We're sorry, but you've reached the end of search results.",position:"bottomCenter"}))})},S=()=>{e.searchFormEl.addEventListener("submit",async t=>{if(t.preventDefault(),l=t.target.searchValue.value.trim(),!!f(l)){l&&e.clearBtnForm.classList.add("search-form__btn-clear--visible");try{const o=await y(l,c);if(!$(o)){e.notFoundEl.classList.add("not-found--visible"),e.ulProductEl.innerHTML="";return}e.notFoundEl.classList.remove("not-found--visible"),L(o.products)}catch(o){r.error({message:o})}}})},w=()=>{e.ulProductEl.addEventListener("click",async t=>{const o=t.target.closest("li");if(!o)return;const s=o.dataset.id;if(s){e.modalEl.classList.add("modal--is-open");try{const i=await b(s);v(i)}catch(i){r.error({message:i.message||"Failed to load product"})}}}),e.modalCloseBtn.addEventListener("click",()=>{e.modalEl.classList.remove("modal--is-open"),e.modalListEl.innerHTML=""}),e.modalEl.addEventListener("click",t=>{t.target===e.modalEl&&(e.modalEl.classList.remove("modal--is-open"),e.modalListEl.innerHTML="")})};P();T();_();S();B();w();
//# sourceMappingURL=index.js.map
