export const refs = {
  ulCategorEl: document.querySelector('.categories'),
  ulProductEl: document.querySelector('.products'),
  searchFormEl: document.querySelector('.search-form'),
  clearBtnForm: document.querySelector('.search-form__btn-clear'),
  notFoundEl: document.querySelector('.not-found'),
  modalEl: document.querySelector('.modal'),
  modalCloseBtn: document.querySelector('.modal__close-btn'),
  modalListEl: document.querySelector('.modal-product'),
  loadMoreBtn: document.querySelector('.load-more-btn'),
  loaderEl: document.querySelector('.loader'),
  scrollToTopBtn: document.querySelector('.scroll-top-btn'),
  toggleThemeEl: document.querySelector('.theme-toggle-btn'),
  buyProductsBtn: document.querySelector('.cart-summary__btn'),
  cartCountEl: document.querySelector('[data-cart-count]'),
  productsCountEl: document.querySelector('[data-count]'),
  wishlistCountEl: document.querySelector('[data-wishlist-count]'),
  priceCountEl: document.querySelector('[data-price]'),
};
